### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by hegelsu** [Jvaeyhcd/HcdDateTimePicker#1]
很难找到一个像你这样可以日期和时间都可以处理的了，现在有一个需求，那就是我想选择年月或时分，就是Year-Month和Hour-Minute这两种模式需求，不知道现在就支持了还是可以再丰富下？

**Comment by Jvaeyhcd** [comment]
我会加到todo里面去再丰富一下，谢谢您的建议

发自我的 iPhone

**Comment by Jvaeyhcd** [comment]
您好，我已经根据你的建议做了修改，您可以到Github上查看最新代码，最终返回的是字符串值

发自我的 iPhone

**Comment by hegelsu** [comment]
太好了，收下了，非常感谢。
