### ISSUE TITLE
ios10上崩溃，cocoa pods是否更新？

### ISSUE THREAD

**Issue by DazenD** [Jvaeyhcd/HcdDateTimePicker#14]
你好，应用已经上线，但是发现ios10上会崩溃，看到之前已经有人提出这个问题，search了一下，发现该库没有更新吧。。比较急，谢谢

**Comment by Jvaeyhcd** [comment]
好的今天我更新一个cocoapods，修复了iOS10奔溃的问题

**Comment by Jvaeyhcd** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  HcdDateTimePicker (1.1.1) successfully published
 📅  December 22nd, 04:24
 🌎  https://cocoapods.org/pods/HcdDateTimePicker
 👍  Tell your friends!
--------------------------------------------------------------------------------
