### ISSUE TITLE
啥时候能把代码更新下啊

### ISSUE THREAD

**Issue by hegelsu** [Jvaeyhcd/HcdDateTimePicker#7]
git上的不对啊，麻烦了

**Comment by Jvaeyhcd** [comment]
最近没有什么时间来更新代码了，如果您有什么新的需求可以fork，然后根据自己的需求修改哦

**Comment by hegelsu** [comment]
前提是你的代码得能先跑起来哦，你git下来看看，都跑不动哇

**Comment by Jvaeyhcd** [comment]
@hegelsu 文件没有传完，这下就尴尬了😅😅😅😅😅😅😅😅

**Comment by hegelsu** [comment]
好，我稍候检查一下。
